### **SVM TEXT CLASSIFICATION**

In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [113]:
dataset=pd.read_csv('spam.csv', encoding='latin-1')
dataset.head()

label  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [114]:
dataset.shape

(5572, 5)

In [115]:

dataset=dataset.replace({'label':'spam'},1)
dataset=dataset.replace({'label':'ham'},0)

In [116]:
dataset.head()

label  ... Unnamed: 4
0      0  ...        NaN
1      0  ...        NaN
2      1  ...        NaN
3      0  ...        NaN
4      0  ...        NaN

[5 rows x 5 columns]

In [117]:
x=dataset['text']
y=dataset['label']



In [118]:
vectorizer = TfidfVectorizer(stop_words='english')
vectorized_data=vectorizer.fit_transform(x for x in x)

vectorized_data = pd.DataFrame(vectorized_data.toarray())
print(vectorized_data.head())

#obtaining the token names

tdfidf_tokens=vectorizer.get_feature_names()
vectorized_data=vectorized_data.set_axis(tdfidf_tokens,axis=1,inplace=False)


print(vectorized_data.head())


   0     1     2     3     4     5     ...  8398  8399  8400  8401  8402  8403
0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
1   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
2   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
3   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
4   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0

[5 rows x 8404 columns]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


    00  000  000pes  008704050406  0089  ...  ûªve   ûï  ûïharry   ûò  ûówell
0  0.0  0.0     0.0           0.0   0.0  ...   0.0  0.0      0.0  0.0     0.0
1  0.0  0.0     0.0           0.0   0.0  ...   0.0  0.0      0.0  0.0     0.0
2  0.0  0.0     0.0           0.0   0.0  ...   0.0  0.0      0.0  0.0     0.0
3  0.0  0.0     0.0           0.0   0.0  ...   0.0  0.0      0.0  0.0     0.0
4  0.0  0.0     0.0           0.0   0.0  ...   0.0  0.0      0.0  0.0     0.0

[5 rows x 8404 columns]


In [119]:
x_train,x_test,y_train,y_test=train_test_split(vectorized_data,y,test_size=0.2)

## **Linear SVM**

In [120]:
svc=SVC(kernel='linear')
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [121]:
y_predict=svc.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [122]:
print(confusion_matrix(y_test,y_predict))

[[972   1]
 [ 14 128]]


In [123]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.99      0.90      0.94       142

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



**Accuracy**

In [124]:
r=accuracy_score(y_test,y_predict)
print(r*100,"%")

98.65470852017937 %


## **K SVM**

# **RBF KERNEL**

In [125]:
poly_classification=SVC(kernel='rbf',random_state=0, gamma=1, C=1)
poly_classification.fit(x_train,y_train)

SVC(C=1, gamma=1, random_state=0)

In [126]:
y_predict=svc.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [127]:
print(confusion_matrix(y_test,y_predict))

[[972   1]
 [ 14 128]]


In [128]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.99      0.90      0.94       142

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



**Accuracy**

In [129]:
r=accuracy_score(y_test,y_predict)
print(r*100,"%")

98.65470852017937 %


# **POLYNIMIAL KERNEL**

In [130]:
poly_classification=SVC(kernel='poly',degree=2)
poly_classification.fit(x_train,y_train)

SVC(degree=2, kernel='poly')

In [131]:
y_predict=svc.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [132]:
print(confusion_matrix(y_test,y_predict))


[[972   1]
 [ 14 128]]


In [133]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.99      0.90      0.94       142

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



**Accuracy**

In [134]:
r=accuracy_score(y_test,y_predict)
print(r*100,"%")

98.65470852017937 %
